const ORDER_TYPES = {
  REG_DATE_ASC: 'REG_DATE_ASC', // 오래된 순
  REG_DATE_DESC: 'REG_DATE_DESC', // 최신순
  DISTANCE_ASC: 'DISTANCE_ASC', // 가까운 순
  DISTANCE_DESC: 'DISTANCE_DESC', // 먼 순
  RATING_ASC: 'RATING_ASC',
  RATING_DESC: 'RATING_DESC',
  REVIEW_CNT_ASC: 'REVIEW_CNT_ASC',
  REVIEW_CNT_DESC: 'REVIEW_CNT_DESC',
};
export default ORDER_TYPES;
